alert('Бренданом Эйхом')
alert('У Эйха было всего около 10 дней, чтобы создать первую версию языка')
alert('1995')
alert('JavaScript — это не Java')
alert('Спецификация JavaScript называется ECMAScript')